// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReturnTheFavour.Infrastructure.Data;

#nullable disable

namespace ReturnTheFavour.Infrastructure.Migrations
{
    [DbContext(typeof(ReturnTheFavourDbContext))]
    [Migration("20230606035807_ReturnTheFavour_Initial")]
    partial class ReturnTheFavourInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ReturnTheFavour")
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReturnTheFavour.Core.AggregatesModel.MeasurementAggregate.Measurement", b =>
                {
                    b.Property<Guid>("MeasurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("MeasurementId");

                    b.ToTable("Measurements", "ReturnTheFavour");
                });
#pragma warning restore 612, 618
        }
    }
}
